### ISSUE TITLE
Error on W3 script "w3-include-html"

### ISSUE THREAD

**Issue by mrakcw** [celian-rib/vscode-webvalidation-extension#5]
Hi, sometimes I use a script from w3 when building a layout. 
I was surprised that it is not validating. 
Do you have any ideas?

[Screenshot](http://prntscr.com/zt4nbg)

[Source script w3-include-html](https://www.w3schools.com/howto/howto_html_include.asp)

**Comment by celian-rib** [comment]
Hi @mrakcw  ,your file is not validating because you are using the html attribute w3-include-html that does not exist. 
More infos that may help you here : 

https://stackoverflow.com/questions/50598507/w3-include-html-causing-error-in-validation-from-https-validator-w3-org

Also W3School is not affiliated with the W3C, so i guess sometimes they does not respect all this little tricky rules set by the W3C organization.

Thank you for using my extension, tell me if you need any more informations or help 😄
